package com.example.elderhelpprototypev01.ui.localization

data class AppStrings(
    val appSubtitle: String,
    val statusText: String,
    val listeningText: String,
    val tapToSpeak: String,
    val tapToStop: String,
    val micSubtitle: String,
    val exploreTasks: String,
    val seeAll: String,
    val doctorTitle: String,
    val doctorSubtitle: String,
    val doctorBtn: String,
    val billsTitle: String,
    val billsSubtitle: String,
    val billsBtn: String,
    val formsTitle: String,
    val formsSubtitle: String,
    val formsBtn: String,
    val helpTitle: String,
    val helpSubtitle: String,
    val helpBtn: String,
    val navHome: String,
    val navVoice: String,
    val navServices: String,
    val navSettings: String,
    val welcomePill: String,
    val settingsTitle: String,
    val settingsSubtitle: String,
    val prefLanguageTitle: String,
    val emergencySos: String = "EMERGENCY SOS",
    val cancel: String = "Cancel"
)

object Localization {
    fun getStrings(language: String): AppStrings = when {
        language.contains("Hindi") || language.contains("हिंदी") -> AppStrings(
            appSubtitle = "आपका डिजिटल साथी",
            statusText = "मैं आपकी मदद के लिए यहाँ हूँ।",
            listeningText = "ध्यान से सुन रहा हूँ...",
            tapToSpeak = "बोलने के लिए टैप करें",
            tapToStop = "रोकने के लिए टैप करें",
            micSubtitle = "Sahaay से पूछने के लिए बटन दबाएं",
            exploreTasks = "त्वरित सेवाएँ",
            seeAll = "सभी देखें",
            doctorTitle = "डॉक्टर अपॉइंटमेंट",
            doctorSubtitle = "क्लिनिक विजिट बुक करें",
            doctorBtn = "बुक करें",
            billsTitle = "बिल भुगतान",
            billsSubtitle = "बिजली और पानी का बिल",
            billsBtn = "भुगतान करें",
            formsTitle = "सरकारी फॉर्म्स",
            formsSubtitle = "पेंशन और आईडी फॉर्म्स",
            formsBtn = "खोलें",
            helpTitle = "आपातकालीन सहायता",
            helpSubtitle = "तुरंत सहायता प्राप्त करें",
            helpBtn = "मदद लें",
            navHome = "होम",
            navVoice = "आवाज़",
            navServices = "सेवाएँ",
            navSettings = "सेटिंग्स",
            welcomePill = "नमस्ते! स्वागत है",
            settingsTitle = "सेटिंग्स",
            settingsSubtitle = "पसंद और आपातकालीन सेटअप",
            prefLanguageTitle = "पसंदीदा भाषा"
        )
        language.contains("Marathi") || language.contains("मराठी") -> AppStrings(
            appSubtitle = "तुमचा डिजिटल साथीदार",
            statusText = "मी तुमच्या मदतीसाठी येथे आहे.",
            listeningText = "लक्षपूर्वक ऐकत आहे...",
            tapToSpeak = "बोलण्यासाठी टॅप करा",
            tapToStop = "थांबवण्यासाठी टॅप करा",
            micSubtitle = "Sahaay ला विचारण्यासाठी बटण दाबा",
            exploreTasks = "जलद सेवा",
            seeAll = "सर्व पहा",
            doctorTitle = "डॉक्टर अपॉइंटमेंट",
            doctorSubtitle = "क्लिनिक भेट बुक करा",
            doctorBtn = "बुक करा",
            billsTitle = "बिल भरणा",
            billsSubtitle = "वीज आणि पाणी बिल",
            billsBtn = "बिल भरा",
            formsTitle = "शासकीय फॉर्म",
            formsSubtitle = "पेन्शन आणि आयडी फॉर्म",
            formsBtn = "उघडा",
            helpTitle = "तातडीची मदत",
            helpSubtitle = "त्वरित मदत मिळवा",
            helpBtn = "मदत घ्या",
            navHome = "मुख्य",
            navVoice = "आवाज",
            navServices = "सेवा",
            navSettings = "सेटिंग्ज",
            welcomePill = "नमस्कार! स्वागत आहे",
            settingsTitle = "सेटिंग्ज",
            settingsSubtitle = "पसंती आणि आपत्कालीन सेटअप",
            prefLanguageTitle = "पसंतीची भाषा"
        )
        language.contains("Tamil") || language.contains("தமிழ்") -> AppStrings(
            appSubtitle = "உங்கள் டிஜிட்டல் தோழன்",
            statusText = "நான் உங்களுக்கு உதவ இங்கே இருக்கிறேன்.",
            listeningText = "கவனமாகக் கேட்கிறது...",
            tapToSpeak = "பேச தட்டவும்",
            tapToStop = "நிறுத்த தட்டவும்",
            micSubtitle = "Sahaay இடம் கேட்க பொத்தானை அழுத்தவும்",
            exploreTasks = "விரைவான சேவைகள்",
            seeAll = "அனைத்தும் காண்க",
            doctorTitle = "மருத்துவர் சந்திப்பு",
            doctorSubtitle = "சந்திப்பை முன்பதிவு செய்ய",
            doctorBtn = "முன்பதிவு",
            billsTitle = "கட்டணம் செலுத்த",
            billsSubtitle = "மின்சாரம் மற்றும் குடிநீர்",
            billsBtn = "செலுத்து",
            formsTitle = "அரசு படிவங்கள்",
            formsSubtitle = "ஓய்வூதியம் மற்றும் சான்றிதழ்",
            formsBtn = "திறக்கவும்",
            helpTitle = "அவசர உதவி",
            helpSubtitle = "உடனடி உதவி பெற",
            helpBtn = "உதவி",
            navHome = "முகப்பு",
            navVoice = "குரல்",
            navServices = "சேவைகள்",
            navSettings = "அமைப்புகள்",
            welcomePill = "வணக்கம்! நல்வரவு",
            settingsTitle = "அமைப்புகள்",
            settingsSubtitle = "விருப்பத்தேர்வுகள் & அவசரநிலை",
            prefLanguageTitle = "விருப்பமான மொழி"
        )
        language.contains("Telugu") || language.contains("తెలుగు") -> AppStrings(
            appSubtitle = "మీ డిజిటల్ తోడు",
            statusText = "నేను మీకు సహాయం చేయడానికి ఇక్కడ ఉన్నాను.",
            listeningText = "శ్రద్ధగా వింటున్నాను...",
            tapToSpeak = "మాట్లాడటానికి నొక్కండి",
            tapToStop = "ఆపడానికి నొక్కండి",
            micSubtitle = "Sahaay ని అడగడానికి బటన్ నొక్కండి",
            exploreTasks = "వేగవంతమైన సేవలు",
            seeAll = "అన్నీ చూడండి",
            doctorTitle = "డాక్టర్ అపాయింట్‌మెంట్",
            doctorSubtitle = "క్లినిక్ విజిట్ బుక్ చేయండి",
            doctorBtn = "బుక్ చేయండి",
            billsTitle = "బిల్లు చెల్లింపు",
            billsSubtitle = "కరెంట్ మరియు మంచినీటి బిల్లు",
            billsBtn = "చెల్లించండి",
            formsTitle = "ప్రభుత్వ ఫారాలు",
            formsSubtitle = "పెన్షన్ మరియు ఐడీ ఫారాలు",
            formsBtn = "తెరిచి చూడండి",
            helpTitle = "అత్యవసర సహాయం",
            helpSubtitle = "తక్షణ సహాయం పొందండి",
            helpBtn = "సహాయం",
            navHome = "హోమ్",
            navVoice = "వాయిస్",
            navServices = "సేవలు",
            navSettings = "సెట్టింగ్స్",
            welcomePill = "నమస్కారం! స్వాగతం",
            settingsTitle = "సెట్టింగ్స్",
            settingsSubtitle = "అభిరుచులు & అత్యవసర విభాగాలు",
            prefLanguageTitle = "ఎంచుకున్న భాష"
        )
        language.contains("Bengali") || language.contains("বাংলা") -> AppStrings(
            appSubtitle = "আপনার ডিজিটাল সঙ্গী",
            statusText = "আমি আপনাকে সাহায্য করতে এখানে আছি।",
            listeningText = "মনোযোগ দিয়ে শুনছি...",
            tapToSpeak = "কথা বলতে ট্যাপ করুন",
            tapToStop = "থামাতে ট্যাপ করুন",
            micSubtitle = "Sahaay কে জিজ্ঞাসা করতে বোতামটি চাপুন",
            exploreTasks = "দ্রুত পরিষেবা",
            seeAll = "সব দেখুন",
            doctorTitle = "ডাক্তারের অ্যাপয়েন্টমেন্ট",
            doctorSubtitle = "ক্লিনিক ভিজিট বুক করুন",
            doctorBtn = "বুক করুন",
            billsTitle = "বিল পরিশোধ",
            billsSubtitle = "বিদ্যুৎ ও জলের বিল",
            billsBtn = "পরিশোধ করুন",
            formsTitle = "সরকারি ফর্ম",
            formsSubtitle = "পেনশন ও আইডি ফর্ম",
            formsBtn = "খুলুন",
            helpTitle = "জরুরি সহায়তা",
            helpSubtitle = "তাত্ক্ষণিক সহায়তা পান",
            helpBtn = "সাহায্য নিন",
            navHome = "হোম",
            navVoice = "ভয়েস",
            navServices = "পরিষেবা",
            navSettings = "সেটিংস",
            welcomePill = "নমস্কার! স্বাগতম",
            settingsTitle = "সেটিংস",
            settingsSubtitle = "পছন্দ এবং জরুরি সেটআপ",
            prefLanguageTitle = "পছন্দের ভাষা"
        )
        else -> AppStrings(
            appSubtitle = "Your digital companion",
            statusText = "I'm here to help.",
            listeningText = "Listening carefully...",
            tapToSpeak = "Tap to speak",
            tapToStop = "Tap to stop",
            micSubtitle = "Press the button to ask Sahaay",
            exploreTasks = "Explore Quick Tasks",
            seeAll = "See all",
            doctorTitle = "Doctor Appointment",
            doctorSubtitle = "Book clinic visits",
            doctorBtn = "Book",
            billsTitle = "Pay Bills",
            billsSubtitle = "Electricity & water",
            billsBtn = "Pay",
            formsTitle = "Forms",
            formsSubtitle = "Pension & ID forms",
            formsBtn = "Open",
            helpTitle = "Help",
            helpSubtitle = "Get quick support",
            helpBtn = "Get Help",
            navHome = "Home",
            navVoice = "Voice",
            navServices = "Services",
            navSettings = "Settings",
            welcomePill = "Namaste! Welcome",
            settingsTitle = "Settings",
            settingsSubtitle = "Preferences & Emergency Setup",
            prefLanguageTitle = "Preferred Language"
        )
    }
}
